WITH HACKER_COUNT AS
(
    SELECT 
        H.HACKER_ID, H.NAME, COUNT(*) AS COUNT, COUNT(*) OVER(PARTITION BY COUNT) AS GROUP_COUNT
    FROM 
        HACKERS H
    INNER JOIN 
        CHALLENGES C
    ON 
        H.HACKER_ID = C.HACKER_ID
    GROUP BY 
        H.HACKER_ID, H.NAME
)
SELECT 
    HACKER_ID, NAME, COUNT 
FROM 
    HACKER_COUNT 
WHERE 
    COUNT = (SELECT MAX(COUNT) FROM HACKER_COUNT) OR GROUP_COUNT = 1 
ORDER BY 
    COUNT DESC, HACKER_ID;