SELECT 
    H.HACKER_ID, H.NAME, SUM(S.SCORE) TOTAL_SCORE
FROM 
    HACKERS H
INNER JOIN 
    (SELECT 
        HACKER_ID, CHALLENGE_ID, MAX(SCORE) SCORE
    FROM 
        SUBMISSIONS
    GROUP BY 
        HACKER_ID, CHALLENGE_ID
    HAVING 
        MAX(SCORE) != 0) S
ON
    H.HACKER_ID = S.HACKER_ID
GROUP BY 
    H.HACKER_ID, H.NAME
ORDER BY 
    TOTAL_SCORE DESC, H.HACKER_ID;