SELECT 
    W.ID, R.AGE, R.COIN, R.POWER
FROM
    WANDS W
JOIN
    (SELECT
        WP.AGE AGE, W.POWER POWER, WP.CODE CODE, MIN(W.COINS_NEEDED) COIN
    FROM
        WANDS W
    JOIN
        (SELECT * FROM WANDS_PROPERTY WHERE IS_EVIL = 0) WP
    ON 
        W.CODE = WP.CODE
    GROUP BY 
        AGE, POWER, CODE) R
ON 
    W.COINS_NEEDED = R.COIN AND W.POWER = R.POWER AND W.CODE = R.CODE
ORDER BY 
    W.POWER DESC, R.AGE DESC;