SET @INDEX:=0;

WITH DIFF_RESULT AS 
(
    SELECT 
        TASK_ID, START_DATE, END_DATE, DATEDIFF(START_DATE, LAG(END_DATE, 1) OVER(ORDER BY START_DATE)) AS DIFF
    FROM 
        PROJECTS
)

SELECT 
    MIN(DR.START_DATE), MAX(DR.END_DATE)
FROM 
    (SELECT
        START_DATE, END_DATE, 
        CASE WHEN DIFF IS NULL THEN @INDEX
        WHEN DIFF = 0 THEN @INDEX
        WHEN DIFF > 0 THEN @INDEX:=@INDEX+1 
        END AS GROUP_DIFF
     FROM 
        DIFF_RESULT) DR
GROUP BY 
    DR.GROUP_DIFF
ORDER BY 
    COUNT(*), MIN(DR.START_DATE);