SET @NUM:=0;

WITH FUNCTIONS_NUMBER AS (
    SELECT 
        X, Y, @NUM:=@NUM+1 AS ROWNUM
    FROM FUNCTIONS
)

SELECT 
    DISTINCT F1.X, F1.Y
FROM 
    FUNCTIONS_NUMBER F1
INNER JOIN 
    FUNCTIONS_NUMBER F2
ON 
    F1.X = F2.Y AND F2.X = F1.Y
WHERE 
    F1.ROWNUM != F2.ROWNUM 
    AND
    F1.X <= F1.Y
ORDER BY 
    F1.X;