SET @NUM:=0, @COUNT:= (SELECT COUNT(*) FROM STATION);
SELECT 
    ROUND(SUM(ST.LAT_N), 4) 
FROM 
    (SELECT 
        LAT_N, @NUM:=@NUM+1 AS ROWNUM
    FROM 
        STATION 
    ORDER BY 
        LAT_N) ST
WHERE 
    CASE WHEN @COUNT % 2 = 0 
    THEN ST.ROWNUM BETWEEN @COUNT/2 AND (@COUNT/2)+1 
    ELSE ST.ROWNUM BETWEEN FLOOR((@COUNT/2)+1) AND FLOOR((@COUNT/2)+1) 
    END;
